#!/bin/sh
echo "Content-Type: application/json"
echo "Access-Control-Allow-Origin: *"
echo "Access-Control-Allow-Private-Network: true"
echo "Access-Control-Allow-Headers: *"
echo
if [ -f /tmp/airtime-power-pressed ]; then
  rm -f /tmp/airtime-power-pressed
  echo '{"pressed":true}'
else
  echo '{"pressed":false}'
fi
