#!/bin/sh
echo "Content-Type: application/json"
echo "Access-Control-Allow-Origin: *"
echo "Access-Control-Allow-Private-Network: true"
echo "Access-Control-Allow-Headers: *"
echo
rm -f /tmp/airtime-update.log /tmp/airtime-update.pid
nohup /usr/local/bin/airtime-update > /tmp/airtime-update.log 2>&1 &
echo '{"ok":true}'
